// Hand-rolled stub. Regenerated by wails at build time.
import { main } from '../models'

export function Ping(): Promise<string>
export function GetPaths(): Promise<main.Paths>
export function GetAgents(): Promise<main.AgentInfo[]>
export function GetBrief(name: string): Promise<string>
export function GetMessages(
  view: string,
  recipient: string,
  sender: string,
  subject: string,
  days: number,
  limit: number,
): Promise<main.Message[]>
export function GetMessage(id: string): Promise<main.Message>
export function SendMessage(
  from: string,
  to: string,
  priority: string,
  subject: string,
  body: string,
): Promise<main.SendResult>
export function ReplyMessage(
  from: string,
  inReplyTo: string,
  body: string,
  priority: string,
): Promise<string>
export function SetStatus(id: string, status: string): Promise<void>
export function Approve(id: string): Promise<void>
export function Reject(id: string): Promise<void>
export function GetStats(): Promise<main.Stats>
