// @ts-check
// Hand-rolled stub. Regenerated by wails at build time.
//
// At runtime in the Wails webview, `window.go.main.App` is populated by
// the Wails JS runtime with method bindings to the Go App struct.

export function Ping() { return window['go']['main']['App']['Ping']() }
export function GetPaths() { return window['go']['main']['App']['GetPaths']() }
export function GetAgents() { return window['go']['main']['App']['GetAgents']() }
export function GetBrief(name) { return window['go']['main']['App']['GetBrief'](name) }
export function GetMessages(view, recipient, sender, subject, days, limit) {
  return window['go']['main']['App']['GetMessages'](view, recipient, sender, subject, days, limit)
}
export function GetMessage(id) { return window['go']['main']['App']['GetMessage'](id) }
export function SendMessage(from, to, priority, subject, body) {
  return window['go']['main']['App']['SendMessage'](from, to, priority, subject, body)
}
export function ReplyMessage(from, inReplyTo, body, priority) {
  return window['go']['main']['App']['ReplyMessage'](from, inReplyTo, body, priority)
}
export function SetStatus(id, status) { return window['go']['main']['App']['SetStatus'](id, status) }
export function Approve(id) { return window['go']['main']['App']['Approve'](id) }
export function Reject(id) { return window['go']['main']['App']['Reject'](id) }
export function GetStats() { return window['go']['main']['App']['GetStats']() }
